-- Update AT module configs to use renamed columns
-- ItemId 1 (Communities): CommunityID → Id
-- ItemId 2 (User Community): UserID→UserId, CommunityID→CommunityId, RoleID→RoleId
-- ItemId 1002 (Leden): same as above
-- ItemId 2005 (Groepen): UserCommunity column refs

-- =====================================================
-- ItemId 1 — Communities module (ModuleId 4425)
-- =====================================================
UPDATE AdvancedTable_Items
SET Description = '{"Title":null,"PrimaryKey":null,"Columns":[{"Key":"Name","Label":"Name","Type":"text","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":null,"PatternMessage":null},{"Key":"Slug","Label":"Slug","Type":"text","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":null,"PatternMessage":null}],"AllowCreate":true,"AllowEdit":true,"AllowDelete":true,"AllowBulkDelete":true,"Permissions":null,"Mode":"sql","QuerySelect":"SELECT * FROM Community ORDER BY Id","QueryInsert":"INSERT INTO Community (Name, Slug) VALUES (@Name, @Slug)","QueryUpdate":"UPDATE Community SET Name = @Name, Slug = @Slug WHERE Id = @pk","QueryDelete":"DELETE FROM Community WHERE Id = @pk","QueryBulkDelete":"DELETE FROM Community WHERE Id IN ({ids})","ApiBaseUrl":null,"ApiHeaders":null,"ApiSelectMethod":"GET","ApiInsertMethod":"POST","ApiUpdateMethod":"PUT","ApiDeleteMethod":"DELETE","ApiSelectPath":null,"ApiInsertPath":null,"ApiUpdatePath":null,"ApiDeletePath":null,"IsSql":true,"IsApi":false}'
WHERE ItemId = 1;

PRINT 'ItemId 1 updated';

-- =====================================================
-- ItemId 2 — User Community module (ModuleId 7413)
-- =====================================================
UPDATE AdvancedTable_Items
SET Description = '{"Title":null,"PrimaryKey":null,"Columns":[{"Key":"UserID","Label":"Naam","Type":"select","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":"SELECT u.UserID, u.Username FROM Users u INNER JOIN UserPortals up ON up.UserId = u.UserID WHERE up.PortalId = 0 AND u.UserID NOT IN (SELECT UserId FROM UserCommunity) ORDER BY u.Username","PatternMessage":null},{"Key":"Username","Label":"Naam","Type":"readonly","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":null,"PatternMessage":null},{"Key":"CommunityID","Label":"Community","Type":"multiselect","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":"SELECT Id, Name FROM Community ORDER BY Name","PatternMessage":null}],"AllowCreate":true,"AllowEdit":true,"AllowDelete":true,"AllowBulkDelete":true,"Permissions":null,"Mode":"sql","QuerySelect":"SELECT \r\n    uc.UserId AS UserID,\r\n    u.Username,\r\n    STRING_AGG(CAST(uc.CommunityId AS VARCHAR(20)), '','') AS CommunityID\r\nFROM UserCommunity uc\r\nINNER JOIN Users u ON u.UserID = uc.UserId\r\nGROUP BY uc.UserId, u.Username\r\nORDER BY u.Username","QueryInsert":"DECLARE @lidRid INT = (SELECT RoleID FROM Roles WHERE RoleName = ''Lid'' AND PortalID = 0);\r\nINSERT INTO UserCommunity (UserId, CommunityId, RoleId)\r\nSELECT CAST(@UserID AS INT), CAST(value AS INT), @lidRid\r\nFROM STRING_SPLIT(@CommunityID, '','' )\r\nWHERE RTRIM(LTRIM(value)) <> ''''","QueryUpdate":"DECLARE @lidRid INT = (SELECT RoleID FROM Roles WHERE RoleName = ''Lid'' AND PortalID = 0);\r\nDELETE FROM UserCommunity WHERE UserId = CAST(@pk AS INT);\r\nINSERT INTO UserCommunity (UserId, CommunityId, RoleId)\r\nSELECT CAST(@UserID AS INT), CAST(value AS INT), @lidRid\r\nFROM STRING_SPLIT(@CommunityID, '','' )\r\nWHERE RTRIM(LTRIM(value)) <> ''''","QueryDelete":"DELETE FROM UserCommunity WHERE UserId = CAST(@pk AS INT)","QueryBulkDelete":"DELETE FROM UserCommunity WHERE UserId IN ({ids})","ApiBaseUrl":null,"ApiHeaders":null,"ApiSelectMethod":"GET","ApiInsertMethod":"POST","ApiUpdateMethod":"PUT","ApiDeleteMethod":"DELETE","ApiSelectPath":null,"ApiInsertPath":null,"ApiUpdatePath":null,"ApiDeletePath":null,"IsSql":true,"IsApi":false}'
WHERE ItemId = 2;

PRINT 'ItemId 2 updated';

-- =====================================================
-- ItemId 1002 — Leden module (ModuleId 8417)
-- =====================================================
UPDATE AdvancedTable_Items
SET Description = '{"Title":null,"PrimaryKey":null,"Columns":[{"Key":"UserID","Label":"Gebruiker","Type":"select","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":"SELECT u.UserID, u.DisplayName FROM Users u INNER JOIN UserPortals up ON up.UserId = u.UserID WHERE up.PortalId = 0 AND u.UserID NOT IN (SELECT uc.UserId FROM UserCommunity uc WHERE uc.CommunityId = @rc_CommunityId) ORDER BY u.DisplayName","PatternMessage":null},{"Key":"DisplayName","Label":"Naam","Type":"readonly","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":null,"PatternMessage":null},{"Key":"Email","Label":"E-mail","Type":"email","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":null,"PatternMessage":null},{"Key":"RoleName","Label":"Rol","Type":"select","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":"SELECT r.RoleName, r.RoleName FROM Roles r WHERE r.PortalID = 0 AND r.RoleID > 0 AND r.RoleName NOT LIKE ''Community -%'' ORDER BY r.RoleName","PatternMessage":null},{"Key":"JoinedDate","Label":"Lid sinds","Type":"readonly","Required":false,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":null,"PatternMessage":null}],"AllowCreate":true,"AllowEdit":true,"AllowDelete":true,"AllowBulkDelete":true,"Permissions":null,"Mode":"sql","QuerySelect":"SELECT u.UserID, u.DisplayName, u.Email, ISNULL(r.RoleName, '''') AS RoleName, CONVERT(varchar, u.CreatedOnDate, 105) AS JoinedDate FROM UserCommunity uc INNER JOIN Users u ON u.UserID = uc.UserId LEFT JOIN Roles r ON r.RoleID = uc.RoleId WHERE uc.CommunityId = @rc_CommunityId ORDER BY u.DisplayName","QueryInsert":"DECLARE @rid INT = (SELECT RoleID FROM Roles WHERE RoleName = @RoleName AND PortalID = 0);\r\nINSERT INTO UserCommunity (UserId, CommunityId, RoleId) VALUES (@UserID, @rc_CommunityId, @rid)","QueryUpdate":"DECLARE @newRid INT = (SELECT RoleID FROM Roles WHERE RoleName = @RoleName AND PortalID = 0);\r\nUPDATE UserCommunity SET RoleId = @newRid WHERE UserId = @pk AND CommunityId = @rc_CommunityId","QueryDelete":"DELETE FROM UserCommunity WHERE UserId = @pk AND CommunityId = @rc_CommunityId","QueryBulkDelete":"DELETE FROM UserCommunity WHERE UserId IN ({ids}) AND CommunityId = @rc_CommunityId","ApiBaseUrl":null,"ApiHeaders":null,"ApiSelectMethod":"GET","ApiInsertMethod":"POST","ApiUpdateMethod":"PUT","ApiDeleteMethod":"DELETE","ApiSelectPath":null,"ApiInsertPath":null,"ApiUpdatePath":null,"ApiDeletePath":null,"IsSql":true,"IsApi":false}'
WHERE ItemId = 1002;

PRINT 'ItemId 1002 updated';

-- =====================================================
-- ItemId 2005 — Groepen module (ModuleId 11413)
-- Only the Users column Pattern references UserCommunity
-- =====================================================
UPDATE AdvancedTable_Items
SET Description = '{"Title":"Groepen","PrimaryKey":null,"Columns":[{"Key":"Name","Label":"Naam","Type":"text","Required":true,"Sortable":true,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":null,"PatternMessage":null},{"Key":"Description","Label":"Beschrijving","Type":"text","Required":false,"Sortable":false,"Filterable":false,"Placeholder":null,"MaxLength":null,"Pattern":null,"PatternMessage":null},{"Key":"Users","Label":"Gebruikers","Type":"multiselect","Required":false,"Sortable":false,"Filterable":true,"Placeholder":null,"MaxLength":null,"Pattern":"SELECT u.UserID, u.DisplayName FROM Users u INNER JOIN UserCommunity uc ON uc.UserId = u.UserID WHERE uc.CommunityId = @rc_CommunityId ORDER BY u.DisplayName","PatternMessage":null}],"AllowCreate":true,"AllowEdit":true,"AllowDelete":true,"AllowBulkDelete":true,"Permissions":null,"Mode":"sql","QuerySelect":"SELECT g.Id, g.Name, g.Description, ISNULL(STRING_AGG(CAST(ucg.UserId AS VARCHAR(20)), '',''), '''') AS Users FROM CommunityGroups g LEFT JOIN UserCommunityGroups ucg ON ucg.CommunityGroupId = g.Id WHERE g.CommunityId = @rc_CommunityId GROUP BY g.Id, g.Name, g.Description ORDER BY g.Name","QueryInsert":"INSERT INTO CommunityGroups (CommunityId, Name, Description) VALUES (@rc_CommunityId, @Name, @Description);\nDECLARE @gid INT = SCOPE_IDENTITY();\nINSERT INTO UserCommunityGroups (UserId, CommunityGroupId)\nSELECT CAST(value AS INT), @gid\nFROM STRING_SPLIT(@Users, '','')\nWHERE RTRIM(LTRIM(value)) <> ''''","QueryUpdate":"UPDATE CommunityGroups SET Name = @Name, Description = @Description WHERE Id = @pk;\nDELETE FROM UserCommunityGroups WHERE CommunityGroupId = @pk;\nINSERT INTO UserCommunityGroups (UserId, CommunityGroupId)\nSELECT CAST(value AS INT), @pk\nFROM STRING_SPLIT(@Users, '','')\nWHERE RTRIM(LTRIM(value)) <> ''''","QueryDelete":"DELETE FROM UserCommunityGroups WHERE CommunityGroupId = @pk;\nDELETE FROM CommunityGroups WHERE Id = @pk","QueryBulkDelete":"DELETE FROM UserCommunityGroups WHERE CommunityGroupId IN ({ids});\nDELETE FROM CommunityGroups WHERE Id IN ({ids})","ApiBaseUrl":null,"ApiHeaders":null,"ApiSelectMethod":"GET","ApiInsertMethod":"POST","ApiUpdateMethod":"PUT","ApiDeleteMethod":"DELETE","ApiSelectPath":null,"ApiInsertPath":null,"ApiUpdatePath":null,"ApiDeletePath":null,"IsSql":true,"IsApi":false}'
WHERE ItemId = 2005;

PRINT 'ItemId 2005 updated';
PRINT 'All AT configs updated';
